### ISSUE TITLE
Change testGroup to standard group() syntax

### ISSUE THREAD

**Issue by johnpryan** [RedBrogdon/dartpad_test#2]
It would be great if we could match semantics of the test package, e.g.

```
testGroup([...tests])
```

would become:

```
group('tests', () {
  test('a', () {
    expect('a', 'b');
  });
});
```

**Comment by redbrogdon** [comment]
Fixed, at least as far as renaming the method.

Changing the parameter syntax from an array to a single function definition would be significantly trickier, as the real test API relies on some globals in the test runner to track test registrations made from within that function. I'd prefer to avoid mimicking it unless people feel super strongly.
